openapi: 3.0.0
info:
  title: nequiapp
  version: 1.0.0
  description: ''
servers:
  - url: localhost
paths:
  /productos/max-stock/40cc3e6b-4869-4367-850a-9b103e715589:
    parameters: []
    get:
      summary: max-stock
      parameters: []
      responses: {}
  /franquicias:
    parameters: []
    get:
      summary: todas la franquicias
      parameters: []
      responses: {}
    post:
      summary: crear franquicia
      parameters: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
  /sucursales:
    parameters: []
    get:
      summary: todas la sucursales
      parameters: []
      responses: {}
    post:
      summary: agregar sucursal
      parameters: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                franquiciaId:
                  type: string
  /franquicias/40cc3e6b-4869-4367-850a-9b103e715589/nombre:
    parameters: []
    put:
      summary: cambiar nombre franquicia
      parameters: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nuevoNombre:
                  type: string
  /sucursales/cb3ea70a-4d90-49e9-a1f1-4c35283ec749/nombre:
    parameters: []
    put:
      summary: cambiar nombre sucursal
      parameters: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nuevoNombre:
                  type: string
  /productos/3ac9003b-1f48-4883-96c2-2ab114be4ee2/nombre:
    parameters: []
    put:
      summary: cambiar nombre producto
      parameters: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nuevoNombre:
                  type: string
  /productos/d1fc6585-35f2-4dcc-80a8-2563bf29bca0/stock:
    parameters: []
    put:
      summary: actualizar stock producto
      parameters: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stock:
                  type: string
                  format: utc-millisec
  /productos:
    parameters: []
    post:
      summary: agregar producto
      parameters: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                stock:
                  type: string
                  format: color
                sucursalId:
                  type: string
  /productos/d1fc6585-35f2-4dcc-80a8-2563bf29bca0:
    parameters: []
    delete:
      summary: eliminar producto
      parameters: []
      responses: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
