spring:
  data:
    mongodb:
      uri: mongodb+srv://sergiosuarique:3z6repj9e8Vvw84z@cluster0.aalezgz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: nequi

server:
  port: 8080
